language: java
dist: trusty
jdk: oraclejdk11
env:
  global:
    - CC_TEST_REPORTER_ID=8caf97646ab3b3569a638f130a748843cfdfbbdfe70f32a7d24ed58df61d9e43
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn test
after_script:
  - ./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml
  - ./cc-test-reporter upload-coverage -d